create table level (level_id bigint generated by default as identity (start with 1), title varchar(255), primary key (level_id))
create table skill (skill_id bigint generated by default as identity (start with 1), description varchar(255), title varchar(255), primary key (skill_id))
create table skill_level (skill_skill_id bigint not null, levels_level_id bigint not null)
alter table skill_level add constraint UK_l0kqwv4n6pxb2to59hrduugfx  unique (levels_level_id)
alter table skill_level add constraint FK_l0kqwv4n6pxb2to59hrduugfx foreign key (levels_level_id) references level
alter table skill_level add constraint FK_dpo1ra0ygm2ctp73b14d3n1ax foreign key (skill_skill_id) references skill
